version: 1  
services:  
  - type: web  
    name: backend
    env: python  
    plan: free  
    buildCommand: pip install -r requirements.txt  
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT  
    envVars:  
      - key: YOUR_ENV_VARIABLE  
        value: your_value  # Optional: Any environment variables you need